# Generated by Django 3.2.8 on 2021-10-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Palabras',
            fields=[
                ('cod', models.AutoField(primary_key=True, serialize=False)),
                ('palabra1', models.CharField(max_length=100)),
                ('palabra2', models.CharField(max_length=100)),
                ('palabra3', models.CharField(max_length=100)),
                ('palabra4', models.CharField(max_length=100)),
                ('palabra5', models.CharField(max_length=100)),
                ('palabra6', models.CharField(max_length=100)),
                ('palabra7', models.CharField(max_length=100)),
                ('palabra8', models.CharField(max_length=100)),
                ('palabra9', models.CharField(max_length=100)),
                ('palabra10', models.CharField(max_length=100)),
                ('palabra11', models.CharField(max_length=100)),
                ('palabra12', models.CharField(max_length=100)),
                ('palabra13', models.CharField(max_length=100)),
                ('palabra14', models.CharField(max_length=100)),
                ('palabra15', models.CharField(max_length=100)),
                ('palabra16', models.CharField(max_length=100)),
                ('palabra17', models.CharField(max_length=100)),
                ('palabra18', models.CharField(max_length=100)),
                ('palabra19', models.CharField(max_length=100)),
                ('palabra20', models.CharField(max_length=100)),
                ('palabra21', models.CharField(max_length=100)),
                ('palabra22', models.CharField(max_length=100)),
                ('palabra23', models.CharField(max_length=100)),
                ('palabra24', models.CharField(max_length=100)),
                ('palabra25', models.CharField(max_length=100)),
                ('palabra26', models.CharField(max_length=100)),
                ('palabra27', models.CharField(max_length=100)),
                ('palabra28', models.CharField(max_length=100)),
                ('palabra29', models.CharField(max_length=100)),
                ('palabra30', models.CharField(max_length=100)),
                ('palabra31', models.CharField(max_length=100)),
                ('palabra32', models.CharField(max_length=100)),
                ('palabra33', models.CharField(max_length=100)),
                ('palabra34', models.CharField(max_length=100)),
                ('palabra35', models.CharField(max_length=100)),
                ('palabra36', models.CharField(max_length=100)),
                ('palabra37', models.CharField(max_length=100)),
                ('palabra38', models.CharField(max_length=100)),
                ('palabra39', models.CharField(max_length=100)),
                ('palabra40', models.CharField(max_length=100)),
                ('palabra41', models.CharField(max_length=100)),
                ('palabra42', models.CharField(max_length=100)),
                ('palabra43', models.CharField(max_length=100)),
                ('palabra44', models.CharField(max_length=100)),
                ('palabra45', models.CharField(max_length=100)),
                ('palabra46', models.CharField(max_length=100)),
                ('palabra47', models.CharField(max_length=100)),
                ('palabra48', models.CharField(max_length=100)),
                ('palabra49', models.CharField(max_length=100)),
                ('palabra50', models.CharField(max_length=100)),
                ('palabra51', models.CharField(max_length=100)),
                ('palabra52', models.CharField(max_length=100)),
            ],
        ),
    ]
