from django.db import models

# Create your models here.
class Palabras(models.Model):
    cod = models.AutoField(primary_key=True)
    palabra1 = models.CharField(max_length=100, blank=False, null=False)
    palabra2 = models.CharField(max_length=100, blank=False, null=False)
    palabra3 = models.CharField(max_length=100, blank=False, null=False)
    palabra4 = models.CharField(max_length=100, blank=False, null=False)
    palabra5 = models.CharField(max_length=100, blank=False, null=False)
    palabra6 = models.CharField(max_length=100, blank=False, null=False)
    palabra7 = models.CharField(max_length=100, blank=False, null=False)
    palabra8 = models.CharField(max_length=100, blank=False, null=False)
    palabra9 = models.CharField(max_length=100, blank=False, null=False)
    palabra10 = models.CharField(max_length=100, blank=False, null=False)
    palabra11= models.CharField(max_length=100, blank=False, null=False)
    palabra12 = models.CharField(max_length=100, blank=False, null=False)
    palabra13 = models.CharField(max_length=100, blank=False, null=False)
    palabra14 = models.CharField(max_length=100, blank=False, null=False)
    palabra15 = models.CharField(max_length=100, blank=False, null=False)
    palabra16 = models.CharField(max_length=100, blank=False, null=False)
    palabra17 = models.CharField(max_length=100, blank=False, null=False)
    palabra18 = models.CharField(max_length=100, blank=False, null=False)
    palabra19 = models.CharField(max_length=100, blank=False, null=False)
    palabra20 = models.CharField(max_length=100, blank=False, null=False)
    palabra21 = models.CharField(max_length=100, blank=False, null=False)
    palabra22 = models.CharField(max_length=100, blank=False, null=False)
    palabra23 = models.CharField(max_length=100, blank=False, null=False)
    palabra24 = models.CharField(max_length=100, blank=False, null=False)
    palabra25 = models.CharField(max_length=100, blank=False, null=False)
    palabra26 = models.CharField(max_length=100, blank=False, null=False)
    palabra27 = models.CharField(max_length=100, blank=False, null=False)
    palabra28 = models.CharField(max_length=100, blank=False, null=False)
    palabra29 = models.CharField(max_length=100, blank=False, null=False)
    palabra30 = models.CharField(max_length=100, blank=False, null=False)
    palabra31 = models.CharField(max_length=100, blank=False, null=False)
    palabra32= models.CharField(max_length=100, blank=False, null=False)
    palabra33 = models.CharField(max_length=100, blank=False, null=False)
    palabra34 = models.CharField(max_length=100, blank=False, null=False)
    palabra35 = models.CharField(max_length=100, blank=False, null=False)
    palabra35 = models.CharField(max_length=100, blank=False, null=False)
    palabra36 = models.CharField(max_length=100, blank=False, null=False)
    palabra37 = models.CharField(max_length=100, blank=False, null=False)
    palabra38 = models.CharField(max_length=100, blank=False, null=False)
    palabra39 = models.CharField(max_length=100, blank=False, null=False)
    palabra40 = models.CharField(max_length=100, blank=False, null=False)
    palabra41 = models.CharField(max_length=100, blank=False, null=False)
    palabra42 = models.CharField(max_length=100, blank=False, null=False)
    palabra43 = models.CharField(max_length=100, blank=False, null=False)
    palabra44 = models.CharField(max_length=100, blank=False, null=False)
    palabra45 = models.CharField(max_length=100, blank=False, null=False)
    palabra46 = models.CharField(max_length=100, blank=False, null=False)
    palabra47 = models.CharField(max_length=100, blank=False, null=False)
    palabra48 = models.CharField(max_length=100, blank=False, null=False)
    palabra49 = models.CharField(max_length=100, blank=False, null=False)
    palabra50 = models.CharField(max_length=100, blank=False, null=False)
